version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:  
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data:

